---
driver:
  # name: ec2
  name: vagrant
  customize:
    memory: 1024
  # tags:
  #   Name: test-et-zookeeper
  #   Role: et_zookeeper Testing
  #   Env: dev
  #   created-by: test-kitchen

provisioner:
  name: chef_zero
  encrypted_data_bag_secret_key_path: ~/.chef/encrypted_data_bag_secret
  data_bags_path: <%= ENV['CHEF_REPO'] %>/data_bags
  environments_path: <%= ENV['CHEF_REPO'] %>/environments
  client_rb:
    environment: '_default'

platforms:
- name: ubuntu-12.04

suites:
- name: default
  run_list: recipe[et_zookeeper]
