---
driver:
  name: vagrant
  customize:
    memory: 2048
  # name: ec2
  # tags:
  #   Name: test-et-zookeeper
  #   Role: et_zookeeper Testing
  #   Env: dev
  #   created-by: test-kitchen

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-14.04

suites:
- name: default
  run_list: recipe[et_zookeeper]
