---
driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  security_group_ids: ['ci-testing']
  image_id: ami-bbef47d0
  instance_type: m1.large
  interface: public
  transport:
    ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  tags:
    Name: test-et-zookeeper
    Env: public
    Type: test
    created-by: test-kitchen
  iam_profile_name: zookeeper

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-14.04

suites:
- name: default
  run_list: recipe[et_zookeeper]
