---
driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  security_group_ids: ['ci-testing']
  image_id: ami-bbef47d0
  instance_type: m1.large
  interface: public
  tags:
    Name: test-et-zookeeper
    Env: public
    Type: test
    created-by: test-kitchen
    Operator: <%= ENV['USER'] %>
  iam_profile_name: zookeeper

transport:
  name: sftp
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-14.04

suites:
- name: default
  run_list:
    - recipe[et_monitoring::agent]
    - recipe[et_zookeeper]
    - recipe[datadog_client::default]
  attributes:
    newrelic:
      server_monitor_agent:
        service_notify_action: nothing
        service_actions:
          - enable
