language: ruby
cache:
  directories:
  - "$HOME/.berkshelf"
addons:
  apt:
    sources:
    - chef-stable-precise
    packages:
    - chefdk
rvm:
- 2.2
before_install:
- openssl aes-256-cbc -K $encrypted_46d15d91d991_key -iv $encrypted_46d15d91d991_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv .chef ~/.chef
- mv .ssh/travis_ci_ec2.pem ~/.ssh/travis_ci_ec2.pem
- mv .ssh/travis_github ~/.ssh/id_rsa
- mv .ssh/trubot.pem ~/.chef/trubot.pem
- echo 'node_name "trubot"' >> ~/.chef/knife.rb
- echo 'client_key "~/.chef/trubot.pem"' >> ~/.chef/knife.rb
- echo 'chef_server_url "https://api.opscode.com/organizations/evertrue"' >> ~/.chef/knife.rb
- chmod 600 ~/.chef/knife.rb ~/.chef/trubot.pem
- chmod 600 ~/.ssh/travis_ci_ec2.pem ~/.chef/encrypted_data_bag_secret ~/.ssh/id_rsa
install:
- eval "$(chef shell-init bash)"
- chef gem install kitchen-ec2 coveralls kitchen-sync
before_script:
- berks
- chef --version
- rubocop --version
- foodcritic --version
script:
- rubocop
- foodcritic .
- chef exec rspec
- kitchen test -d always
env:
  global:
  - secure: RLoRIE12B08qeHhKZSA/6jnDPsxpRIDH9YpuZm65BQwfZ1RCip4Ax3mSu2Pja+qq3nJXsIou10F/Gj1t+v8NOoyGzZ79mC169TZJK3OaYvyt/Nv7zFgDaesDcYUVNpxWKlDs19VCHvVrTayiX13g9oumwmMnIyTVEJ9wHN5QUAQ=
  - secure: RJo4raLDAGd0ElT2E3bD6u3mERUTBCcZ4cR814L5NBpXVNkaVA4hf92VhngNiR5+arQY9GZ5jkoXTseS2mRbeXmjaf0/mlSFSIrAvfX8VnX1SKEAk+GN8a8dL8AwFzMyTrO5d3jEgZPjPJlrRAB+SxbOHB91LNUxjR6ceDX4gyE=
